replicaCount: 1
image:
  repository: user-app
  tag: latest
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 8000
ingress:
  enabled: true
  host: arch.homework
  path: /
database:
  url: jdbc:postgresql://postgres:5432/user_db
  username: postgres
  password: postgres
  driver: org.postgresql.Driver
config:
  spring:
    jpa:
      hibernate:
        ddl-auto: validate
    flyway:
      enabled: true