apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Chart.Name }}-migrations
spec:
  template:
    spec:
      containers:
        - name: migrate
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          command: ["sh", "-c", "while ! python -c 'import socket; socket.socket(socket.AF_INET, socket.SOCK_STREAM).connect((\"postgres-postgresql\", 5432))' 2>/dev/null; do sleep 1; done && flyway migrate"]
          env:
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Chart.Name }}-db-secret
                  key: url
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Chart.Name }}-db-secret
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Chart.Name }}-db-secret
                  key: password
      restartPolicy: OnFailure