apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config
data:
  prometheus.yml: |
    global:
      scrape_interval: {{ .Values.config.global.scrape_interval }}
      evaluation_interval: {{ .Values.config.global.evaluation_interval }}
    scrape_configs:
      - job_name: 'user-app'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: ['user-app:8000']