apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config
data:
  prometheus.yml: |
    global:
      scrape_interval: {{ .Values.config.global.scrape_interval }}
      evaluation_interval: {{ .Values.config.global.evaluation_interval }}
    scrape_configs:
    - job_name: 'user-app'
      metrics_path: '/actuator/prometheus'
      static_configs:
        - targets: ['user-app:8000']
    - job_name: 'nginx-ingress'
      metrics_path: '/metrics'
      kubernetes_sd_configs:
        - role: pod
          namespaces:
            names: [ingress-nginx]
      relabel_configs:
        - source_labels: [__meta_kubernetes_pod_label_app_kubernetes_io_component]
          action: keep
          regex: controller
        - source_labels: [__meta_kubernetes_pod_container_port_name]
          action: keep
          regex: metrics
          metrics_path: /metrics

    - job_name: 'postgres-exporter'
      metrics_path: '/metrics'
      static_configs:
        - targets: ['user-app-postgres-exporter.user-app.svc.cluster.local:9187']