replicaCount: 1
image:
  repository: prom/prometheus
  tag: v2.47.0
  pullPolicy: IfNotPresent
service:
  type: NodePort
  port: 9090
  nodePort: 30090
ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  hosts:
    - host: prometheus.arch.homework
      paths:
        - path: /
          pathType: Prefix
    - host: localhost
      paths:
        - path: /
          pathType: Prefix
config:
  global:
    scrape_interval: 15s
    evaluation_interval: 15s
  scrape_configs:
    - job_name: 'user-app'
      metrics_path: '/actuator/prometheus'
      static_configs:
        - targets: ['user-app:8000']